export const START_FETCHING = "START_FETCHING";
export const FETCH_DATA = "FETCH_DATA";
export const END_FETCHING = "END_FETCHING";
export const PRODUCTS_ERR_FETCHING = "PRODUCTS_ERR_FETCHING";
export const SINGLE_PRODUCT_START_FETCHING = "SINGLE_PRODUCT_START_FETCHING";
// export const PRODUCTS_ERR_FETCHING = "PRODUCTS_ERR_FETCHING";
export const FETCH_SINGLE_PRODUCT = "FETCH_SINGLE_PRODUCT";
export const SINGLE_PRODUCT_END_FETCHING = "SINGLE_PRODUCT_END_FETCHING";
export const SINGLE_PRODUCT_ERR = "SINGLE_PRODUCT_ERR";
// export const START_FETCHING = "START_FETCHING";
//============================================================================================================
export const INCREMENT_PRODUCT_QUANTITY = "INCREMENT_PRODUCT_QUANTITY";
export const DECCREMENT_PRODUCT_QUANTITY = "DECREMENT_PRODUCT_QUANTITY";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREASE_CART_COUNT = "INCREASE_CART_COUNT";
export const TOGGLE_AMOUNT = " TOGGLE_AMOUNT";
